## Ladda och omarbeta Prisindex

In [1]:
## Om det körs i samma pipeline, behövs det inte köras igen. 
## %run 0.Hämta_Lämna_Minio.ipynb

Requirement already satisfied: sas7bdat in /opt/conda/lib/python3.9/site-packages (2.2.3)
Requirement already satisfied: six>=1.8.0 in /opt/conda/lib/python3.9/site-packages (from sas7bdat) (1.16.0)
Requirement already satisfied: xport in /opt/conda/lib/python3.9/site-packages (3.6.1)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.9/site-packages (from xport) (5.4.1)
Requirement already satisfied: click>=7.1.1 in /opt/conda/lib/python3.9/site-packages (from xport) (8.1.3)
Requirement already satisfied: pandas<1.4,>=1.3.5 in /opt/conda/lib/python3.9/site-packages (from xport) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.9/site-packages (from pandas<1.4,>=1.3.5->xport) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.9/site-packages (from pandas<1.4,>=1.3.5->xport) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /opt/conda/lib/python3.9/site-packages (from pandas<1.4,>=1.3.5->xport) (1.24.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas<1.4,>=1.3.5->xport) (1.16.0)

In [2]:
bucket_namn = "demo-funktionalitet"
file_index = "index_orig.sas7bdat"
file_vikter = "value_orig.sas7bdat"
prisindex1 = read_from_s3(bucket_namn, file_index, datatype="sas")
vikter = read_from_s3(bucket_namn, file_vikter, datatype="sas")

In [3]:
prisindex1.head()

,factKlonKey,Period,VariableId,VariableName,MeasureValue,BranchGroupId,BranchName,BranchCode,OutClass,IsFinal,MarknadCode,MarknadName
0,229117764.0,2013M08,3.0,Prisindex,99.8,143.0,"Elmotorer, generat. batterier, kablar, belys.","27.1-4,9","27.1-4,9|5",0.0,5,Total (=Hemma+Export)
1,229109145.0,2013M11,3.0,Prisindex,99.9,143.0,"Elmotorer, generat. batterier, kablar, belys.","27.1-4,9","27.1-4,9|5",0.0,5,Total (=Hemma+Export)
2,229101477.0,2006M09,3.0,Prisindex,94.9,143.0,"Elmotorer, generat. batterier, kablar, belys.","27.1-4,9","27.1-4,9|5",0.0,5,Total (=Hemma+Export)
3,229122072.0,2002M11,3.0,Prisindex,84.2,143.0,"Elmotorer, generat. batterier, kablar, belys.","27.1-4,9","27.1-4,9|5",0.0,5,Total (=Hemma+Export)
4,229106841.0,2006M03,3.0,Prisindex,90.9,143.0,"Elmotorer, generat. batterier, kablar, belys.","27.1-4,9","27.1-4,9|5",0.0,5,Total (=Hemma+Export)

In [4]:
vikter.tail()

,factKlonKey,Period,VariableId,VariableName,MeasureValue,BranchGroupId,BranchName,BranchCode,OutClass,IsFinal,AttributeCode,AttributeName,MarknadCode,MarknadName,Oms_ttningstypCode,Oms_ttningstypName,Medelfel_f_r_punktskattning_6_1_,Medelfel_f_r_punktskattning_6_10
35187,2.721774e+08,2015M05,17.0,Omsättning,4.250600e+04,3360.0,Övrig tillverkning av transportmedel,30.9,30.9|5|07,1.0,6.1.1.10,"Punktskattning med blankettdata, momsdeklarati...",5,Total (Hemma+Export),07,Handelsomsättning,NaN,0.0
35188,2.095980e+08,2007M08,17.0,Omsättning,0.000000e+00,3360.0,Övrig tillverkning av transportmedel,30.9,30.9|5|06,0.0,6.1.1.10,"Punktskattning med blankettdata, momsdeklarati...",5,Total (Hemma+Export),06,Tjänsteomsättning,NaN,NaN
35189,1.229886e+09,2022M03,17.0,Omsättning,3.718888e+06,3889.0,"Tillverkning av datorer , kommunikationsutrust...",26.5-8,26.5-8|5|08,1.0,6.1.1.10,"Punktskattning med blankettdata, momsdeklarati...",5,Total (Hemma+Export),08,Nettoomsättning,NaN,0.0
35190,1.229886e+09,2022M03,17.0,Omsättning,3.350718e+05,2670.0,"Industri för datorer, elektronikvaror och optik",26,26|5|07,1.0,6.1.1.10,"Punktskattning med blankettdata, momsdeklarati...",5,Total (Hemma+Export),07,Handelsomsättning,NaN,0.0
35191,1.229886e+09,2022M03,17.0,Omsättning,8.953016e+03,4986.0,Industri för elapparatur,27,27|5|06,1.0,6.1.1.10,"Punktskattning med blankettdata, momsdeklarati...",5,Total (Hemma+Export),06,Tjänsteomsättning,NaN,0.0